### ISSUE TITLE
Should there be a `dbs.Textarea` component?

### ISSUE THREAD

**Issue by ned2** [ASIDataScience/dash-bootstrap-components#116]
I tried to use a `dbc.Input` with `type="textarea"` but found that this didn't seem to apply any attributes/styles to make it emulate the behaviour of an actual `textarea` element. So I fell back to using a `dcc.Textarea` component with Bootstrap `form-control` classes. I'm wondering if there should just be a `dbs.Textarea` component or alternatively, making `type="textarea"` emulate a `textarea` element, if that can be done.

**Comment by tcbegley** [comment]
Yes you're right, I think we should provide a separate component like `dash-core-components` does with the Bootstrap styles applied automatically.

**Comment by tcbegley** [comment]
This has been added by #117 and will be available in the next release (probably going to merge #118 before making a new release).

**Comment by ned2** [comment]
Awesome!

**Comment by pbugnion** [comment]
`dbc.TextArea` is now available in dash-bootstrap-components 0.2.7 (available on PyPi).
