### ISSUE TITLE
Add long_description and clean pypi landing page

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dash-bootstrap-components#2]
The [pypi landing page](https://pypi.org/project/dash-bootstrap-components/) doesn't look great at the moment. Adding a `long_description` would go a long way towards solving this.

**Comment by tcbegley** [comment]
I have currently have this setup to just use the README as the long_description. I also changed the url to link to this repo, I think it looks a lot better already, you can see the current state of it for `0.0.2-rc1`

https://pypi.org/project/dash-bootstrap-components/0.0.2rc1/

**Comment by pbugnion** [comment]
Great!
