### ISSUE TITLE
Consistent linting and reformatting rules

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dash-bootstrap-components#24]
I believe we have both been using [black](https://black.readthedocs.io/en/stable/) for formatting Python source code, and mostly sticking to pep 8. For now, the JS source code is mostly fairly self-consistent.

Would it make sense to adopt a consistent code style through reformatters and CI tests? It'd help outside contributors make pull requests that are visually similar to the current codebase. I suggest:
- prettier for the JS, following dash-core-components. See [this PR](https://github.com/plotly/dash-core-components/pull/274).
- black and flake8 for the Python side and the docs, since they're (becoming) the de-facto standard.
- enforcing consistency as part of the CI pipeline.

The timing around this needs to be somewhat well thought through to avoid merge conflicts with existing PRs.

Any thoughts?

**Comment by tcbegley** [comment]
I think this would be great.

Of the two currently open PRs, one is ready to merge and another doesn't affect any of the JS or Python source, so now might be a good opportunity to set something up?

**Comment by pbugnion** [comment]
Great -- I'll add this over the next couple of days.

**Comment by tcbegley** [comment]
Perfect, let me know if I can help at all.

**Comment by pbugnion** [comment]
Closed by PRs #31  and #26 .
