### ISSUE TITLE
Add isort to the CI pipeline?

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dash-bootstrap-components#47]
PR #44 adds `isort` configuration. I don't have any strong preferences, but if we think imports should be sorted, should we add isort checks to the CI pipeline?

If some developers use isort and not others, it will lead to confusing diffs.

**Comment by tcbegley** [comment]
Yeah I guess this makes sense. I don’t have particularly strong preferences either, but occasionally find I sort convenient for organising my imports with minimal effort. I added the configuration because out of the box it clashes with black. Maybe enforcing some consistency is a good thing.

**Comment by tcbegley** [comment]
This has been resolved by #54
