### ISSUE TITLE
Allow dropdowns in input groups

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dash-bootstrap-components#52]
Reactstrap supports dropdowns in input groups (see [docs](https://reactstrap.github.io/components/input-group/), for instance) via the `InputGroupButtonDropdown` component.

This just passes an `addonType` prop to a `Dropdown` component. See:

- the `InputGroupButtonDropdown` [source](https://github.com/reactstrap/reactstrap/blob/master/src/InputGroupButtonDropdown.js)
- how the underlying Dropdown component handles the `addonType` [prop](https://github.com/reactstrap/reactstrap/blob/master/src/Dropdown.js#L215).

I think the easiest would be to add an `addonType` prop to `Dropdown`. I don't think we need to replicate `InputGroupButtonDropdown`, since it just wraps `Dropdown` and we would need to copy all the prop types.

Happy to implement this if we think it's the right thing to do. If we do this, we should amend the documentation on input groups (PR #51 ) to document dropdowns.

**Comment by tcbegley** [comment]
Nice, I think this would be a good addition. I also favour exposing extra options in the api of our `DropdownMenu` component over adding a new component. Very happy for you to have a go at implementing this.

**Comment by pbugnion** [comment]
Closed by PR #59.
